### ISSUE TITLE
依存解析的结果的head对不上！

### ISSUE THREAD

**Issue by Zhangbeibei1991** [onehaitao/SemEval2010-to-TACRED#1]
帖子，提个建设性意见哈，你这个句子在解析的时候没有去掉<e></e>之类的符号，导致依存解析的结果的head根本对不上，有空改一下哈哈

**Comment by onehaitao** [comment]
你指的是<e1>、</e1>、<e2>、</e2>这四个标记吗？

**Comment by onehaitao** [comment]
你指的是&lt;e1&gt;、&lt;/e1&gt;、&lt;e2&gt;、&lt;/e2&gt;这四个标记吗

**Comment by onehaitao** [comment]
> 帖子，提个建设性意见哈，你这个句子在解析的时候没有去掉之类的符号，导致依存解析的结果的head根本对不上，有空改一下哈哈

已更正
